config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :pazientes do
	resources :cartella_clinicas
  end

end

app/models/cartella_clinica.rb
class CartellaClinica < ActiveRecord::Base
belongs_to :paziente
end

app/models/paziente.rb
class Paziente < ActiveRecord::Base
has_many :cartella_clinicas

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartella_clinicas_controller.rb
class CartellaClinicasController < ApplicationController
  before_action :set_cartella_clinica, only: [:show, :edit, :update, :destroy]

  # GET /cartella_clinicas
  # GET /cartella_clinicas.json
  def index
    @cartella_clinicas = CartellaClinica.all
  end

  # GET /cartella_clinicas/1
  # GET /cartella_clinicas/1.json
  def show
  end

  # GET /cartella_clinicas/new
  def new
    @cartella_clinica = CartellaClinica.new
  end

  # GET /cartella_clinicas/1/edit
  def edit
  end

  # POST /cartella_clinicas
  # POST /cartella_clinicas.json
  def create
    @cartella_clinica = CartellaClinica.new(cartella_clinica_params)

    respond_to do |format|
      if @cartella_clinica.save
        format.html { redirect_to @cartella_clinica, notice: 'La Cartella clinica è stata creata correttamente.' }
        format.json { render :show, status: :created, location: @cartella_clinica }
      else
        format.html { render :new }
        format.json { render json: @cartella_clinica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartella_clinicas/1
  # PATCH/PUT /cartella_clinicas/1.json
  def update
    respond_to do |format|
      if @cartella_clinica.update(cartella_clinica_params)
        format.html { redirect_to @cartella_clinica, notice: 'La Cartella clinica è stata modificata correttamente.' }
        format.json { render :show, status: :ok, location: @cartella_clinica }
      else
        format.html { render :edit }
        format.json { render json: @cartella_clinica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartella_clinicas/1
  # DELETE /cartella_clinicas/1.json
  def destroy
    @cartella_clinica.destroy
    respond_to do |format|
      format.html { redirect_to cartella_clinicas_url, notice: 'La Cartella clinica è stata eliminata correttamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartella_clinica
      @cartella_clinica = CartellaClinica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartella_clinica_params
      params.require(:cartella_clinica).permit(:generalità, :anamnesi, :obiettivo, :diagnosi, :terapia, :esiti)
    end
end

app/controllers/pazientes_controller.rb
class PazientesController < ApplicationController
  before_action :set_paziente, only: [:show, :edit, :update, :destroy]

  # GET /pazientes
  # GET /pazientes.json
  def index
    @pazientes = Paziente.all
  end

  # GET /pazientes/1
  # GET /pazientes/1.json
  def show
  end

  # GET /pazientes/new
  def new
    @paziente = Paziente.new
  end

  # GET /pazientes/1/edit
  def edit
  end

  # POST /pazientes
  # POST /pazientes.json
  def create
    @paziente = Paziente.new(paziente_params)

    respond_to do |format|
      if @paziente.save
        format.html { redirect_to @paziente, notice: 'Il Paziente è stato creato correttamente.' }
        format.json { render :show, status: :created, location: @paziente }
      else
        format.html { render :new }
        format.json { render json: @paziente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pazientes/1
  # PATCH/PUT /pazientes/1.json
  def update
    respond_to do |format|
      if @paziente.update(paziente_params)
        format.html { redirect_to @paziente, notice: 'Il Paziente è stato aggiornato correttamente.' }
        format.json { render :show, status: :ok, location: @paziente }
      else
        format.html { render :edit }
        format.json { render json: @paziente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pazientes/1
  # DELETE /pazientes/1.json
  def destroy
    @paziente.destroy
    respond_to do |format|
      format.html { redirect_to pazientes_url, notice: 'Il Paziente è stato eliminato correttamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paziente
      @paziente = Paziente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paziente_params
      params.require(:paziente).permit(:nome, :cognome, :email, :telefono)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartella_clinicas_helper.rb
module CartellaClinicasHelper
end

app/helpers/pazientes_helper.rb
module PazientesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cartella_clinicas/_form.html.erb
<%= form_for(@cartella_clinica) do |f| %>
  <% if @cartella_clinica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cartella_clinica.errors.count, "error") %> prohibited this cartella_clinica from being saved:</h2>

      <ul>
      <% @cartella_clinica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :generalità %><br>
    <%= f.text_area :generalità %>
  </div>
  <div class="field">
    <%= f.label :anamnesi %><br>
    <%= f.text_area :anamnesi %>
  </div>
  <div class="field">
    <%= f.label :obiettivo %><br>
    <%= f.text_area :obiettivo %>
  </div>
  <div class="field">
    <%= f.label :diagnosi %><br>
    <%= f.text_area :diagnosi %>
  </div>
  <div class="field">
    <%= f.label :terapia %><br>
    <%= f.text_area :terapia %>
  </div>
  <div class="field">
    <%= f.label :esiti %><br>
    <%= f.text_area :esiti %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cartella_clinicas/edit.html.erb
<h1>Modifica Cartella Clinica</h1>

<%= render 'form' %>

<%= link_to 'Mostra', @cartella_clinica %> |
<%= link_to 'Indietro', cartella_clinicas_path %>

app/views/cartella_clinicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Cartelle Cliniche</h1>

<table>
  <thead>
    <tr>
      <th>Generalità</th>
      <th>Anamnesi</th>
      <th>Obiettivo</th>
      <th>Diagnosi</th>
      <th>Terapia</th>
      <th>Esiti</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartella_clinicas.each do |cartella_clinica| %>
      <tr>
        <td><%= cartella_clinica.generalità %></td>
        <td><%= cartella_clinica.anamnesi %></td>
        <td><%= cartella_clinica.obiettivo %></td>
        <td><%= cartella_clinica.diagnosi %></td>
        <td><%= cartella_clinica.terapia %></td>
        <td><%= cartella_clinica.esiti %></td>
        <td><%= link_to 'Mostra', cartella_clinica %></td>
        <td><%= link_to 'Modifica', edit_cartella_clinica_path(cartella_clinica) %></td>
        <td><%= link_to 'Elimina', cartella_clinica, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuova Cartella clinica', new_cartella_clinica_path %>

app/views/cartella_clinicas/new.html.erb
<h1>Nuova Cartella Clinica</h1>

<%= render 'form' %>

<%= link_to 'Indietro', cartella_clinicas_path %>

app/views/cartella_clinicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Generalità:</strong>
  <%= @cartella_clinica.generalità %>
</p>

<p>
  <strong>Anamnesi:</strong>
  <%= @cartella_clinica.anamnesi %>
</p>

<p>
  <strong>Obiettivo:</strong>
  <%= @cartella_clinica.obiettivo %>
</p>

<p>
  <strong>Diagnosi:</strong>
  <%= @cartella_clinica.diagnosi %>
</p>

<p>
  <strong>Terapia:</strong>
  <%= @cartella_clinica.terapia %>
</p>

<p>
  <strong>Esiti:</strong>
  <%= @cartella_clinica.esiti %>
</p>

<%= link_to 'Modifica', edit_cartella_clinica_path(@cartella_clinica) %> |
<%= link_to 'Indietro', cartella_clinicas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pazientes/_form.html.erb
<%= form_for(@paziente) do |f| %>
  <% if @paziente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paziente.errors.count, "error") %> prohibited this paziente from being saved:</h2>

      <ul>
      <% @paziente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cognome %><br>
    <%= f.text_field :cognome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pazientes/edit.html.erb
<h1>Modifica Paziente</h1>

<%= render 'form' %>

<%= link_to 'Mostra', @paziente %> |
<%= link_to 'Indietro', pazientes_path %>

app/views/pazientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista dei Pazienti</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Cartella Clinica</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @pazientes.each do |paziente| %>
      <tr>
        <td><%= paziente.nome %></td>
        <td><%= paziente.cognome %></td>
        <td><%= paziente.email %></td>
        <td><%= paziente.telefono %></td>
	<td><%= link_to 'Dettagli', cartella_clinica %></td>
        <td><%= link_to 'Mostra', paziente %></td>
        <td><%= link_to 'Modifica', edit_paziente_path(paziente) %></td>
        <td><%= link_to 'Elimina', paziente, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
	
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuovo Paziente', new_paziente_path %>

app/views/pazientes/new.html.erb
<h1>Nuovo Paziente</h1>

<%= render 'form' %>

<%= link_to 'Indietro', pazientes_path %>

app/views/pazientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paziente.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @paziente.cognome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @paziente.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @paziente.telefono %>
</p>

<%= link_to 'Modifica', edit_paziente_path(@paziente) %> |
<%= link_to 'Indietro', pazientes_path %>

app/views/static_pages/home.html.erb
<% provide(:title, "Fisioterapia Manni") %>

    <h1>Fisioterapia Manni </h1>

</html>